---
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest-arm64
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
      # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
    environment:
      - .env
    volumes:
      - ./palworld:/palworld/